### ISSUE TITLE
Sensitive company information exposed!!

### ISSUE THREAD

**Issue by fwindxox** [shota-imoto/helixf#1]
Hello @shota-imoto!!

We are Insider Threat team from Rakuten Mobile. 
We observed our internal IPv6 address being exposed publicly in your repository. 
Under line 3 in this URL: https://github.com/shota-imoto/helixf/blob/3d19c9b539d5618036c90fb0add947e85366a67f/lib/utils/domain/domain.go

Any company data cannot be exposed publicly and we would like you to take this repository down soon as it is a policy violation. 

Thank you.

**Comment by shota-imoto** [comment]
sorry, i'll delete the IP in today.

**Comment by fwindxox** [comment]
> sorry, i'll delete the IP in today.

Thank you. Please confirm with us back when you deleted it. Thank you

**Comment by shota-imoto** [comment]
@fwindxox 
I deleted.
https://github.com/shota-imoto/helixf/blob/master/lib/utils/domain/domain.go

**Comment by fwindxox** [comment]
Thank you for your quick action!

**Comment by fwindxox** [comment]
Hello @shota-imoto , 

We are still seeing the IPv6 address when we open this link: https://github.com/shota-imoto/helixf/blob/3d19c9b539d5618036c90fb0add947e85366a67f/lib/utils/domain/domain.go  
but we don't see it in the new link you shared. 

Is it possible for you to take down this repository and create another new repository without the IPv6 address? 
We take the security of our data, information systems, and intellectual property seriously. We hope you agree and will help us maintain a strong information security culture at Rakuten Mobile.
